# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1is6EFbal5VR577PSh3dJUqShXppThSAJ
"""

# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZUIv7uig0nVipxCZsVpmxQW5LSQgke6P
"""

#importing libraries
!pip install -q wordcloud
import wordcloud

import nltk
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger') 

import pandas as pd
import matplotlib.pyplot as plt
import io
import unicodedata
import numpy as np
import re
import string



#tokenizing
import nltk
from nltk.tokenize import WhitespaceTokenizer
sentence_data = "The First sentence is about Python. The Second: Shubham lecture. You can learn Python,NLP and Data Ananlysis here. "
sentences = nltk.sent_tokenize(sentence_data)
print (sentences)

tk=WhitespaceTokenizer()
tokens=tk.tokenize(sentence_data)
print(tokens)

# stemming and lemitizing
import nltk
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

paragraph = """Probably the most effective way to achieve paragraph unity is to express the central idea of the paragraph in a topic sentence.

Topic sentences are similar to mini thesis statements. Like a thesis statement, a topic sentence has a specific main point. Whereas the thesis is the main point of the essay, the topic sentence is the main point of the paragraph. Like the thesis statement, a topic sentence has a unifying function. But a thesis statement or topic sentence alone doesn’t guarantee unity. An essay is unified if all the paragraphs relate to the thesis, whereas a paragraph is unified if all the sentences relate to the topic sentence. Note: Not all paragraphs need topic sentences. In particular, opening and closing paragraphs, which serve different functions from body paragraphs, generally don’t have topic sentences.

In academic writing, the topic sentence nearly always works best at the beginning of a paragraph so that the reader knows what to expect:

The embrace of Twitter by politicians and journalists has been one of its most notable features in recent years: for both groups the use of Twitter is becoming close to a requirement.

—Paul Bernal, “A Defence of Responsible Tweeting”

This topic sentence forecasts the central idea or main point of the paragraph: “politicians” and “journalists” rely on Twitter. The rest of the paragraph will focus on these two Twitter-user groups, thereby fulfilling the promise made by the topic sentence. By avoiding irrelevant information that does not relate to the topic sentence, you can compose a unified paragraph."""

# Tokenizing sentences
sentences = nltk.sent_tokenize(paragraph)
print(len(sentences))
stemmer=PorterStemmer()
lemmatizer = WordNetLemmatizer()
# Stemming
for i in range(len(sentences)):
    words = nltk.word_tokenize(sentences[i])
    words = [stemmer.stem(word) for word in words if word not in set(stopwords.words('english'))]
    sentences[i] = ' '.join(words) 

print(sentences) ;
sentences = nltk.sent_tokenize(paragraph)
print(len(sentences))
# Lametizing
for i in range(len(sentences)):
    words = nltk.word_tokenize(sentences[i])
    words = [lemmatizer.lemmatize(word) for word in words if word not in set(stopwords.words('english'))]
    sentences[i] = ' '.join(words) 


print(sentences) ;

import nltk
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

paragraph = """Probably the most effective way to achieve paragraph unity is to express the central idea of the paragraph in a topic sentence.

Topic sentences are similar to mini thesis statements. Like a thesis statement, a topic sentence has a specific main point. Whereas the thesis is the main point of the essay, the topic sentence is the main point of the paragraph. Like the thesis statement, a topic sentence has a unifying function. But a thesis statement or topic sentence alone doesn’t guarantee unity. An essay is unified if all the paragraphs relate to the thesis, whereas a paragraph is unified if all the sentences relate to the topic sentence. Note: Not all paragraphs need topic sentences. In particular, opening and closing paragraphs, which serve different functions from body paragraphs, generally don’t have topic sentences.

In academic writing, the topic sentence nearly always works best at the beginning of a paragraph so that the reader knows what to expect:

The embrace of Twitter by politicians and journalists has been one of its most notable features in recent years: for both groups the use of Twitter is becoming close to a requirement.

—Paul Bernal, “A Defence of Responsible Tweeting”

This topic sentence forecasts the central idea or main point of the paragraph: “politicians” and “journalists” rely on Twitter. The rest of the paragraph will focus on these two Twitter-user groups, thereby fulfilling the promise made by the topic sentence. By avoiding irrelevant information that does not relate to the topic sentence, you can compose a unified paragraph."""



words = nltk.word_tokenize(paragraph)
stemmer=PorterStemmer()
lemmatizer = WordNetLemmatizer()
for w in words:
  if w not in set(stopwords.words('english')):

    print("Actual: %s \nStemmer: %s\nLemmatizer: %s\n"%(w,stemmer.stem(w),lemmatizer.lemmatize(w)))

#31-08-2020 Class Work

import nltk
from nltk.tokenize import WhitespaceTokenizer,WordPunctTokenizer,TreebankWordTokenizer
sentence_data = "This is Shubham's Text isn't it? "

tk=WhitespaceTokenizer()
tokens=tk.tokenize(sentence_data)
print(tokens)
print(len(tokens))

tk=WordPunctTokenizer()
tokens=tk.tokenize(sentence_data)
print(tokens)
print(len(tokens))

tk=TreebankWordTokenizer()
tokens=tk.tokenize(sentence_data)
print(tokens)
print(len(tokens))